services:
  - type: web
    name: twilio-voice-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker app:app
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        value: 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
